#!/bin/python

import subprocess
import os
import threading
import sys
import json
from time import *
term_id=sys.argv[1]
lastinit={}
def update_config(file):
	lastinit[file]=os.path.getmtime(file)

def has_file_changed(file):
	return lastinit[file] != os.path.getmtime(file)

def auto_resize():
	update_config("/tmp/tkTermrs" + term_id)
	while True:
		if has_file_changed("/tmp/tkTermrs" + term_id):
			os.system('printf "$(cat /tmp/tkTermrs' + term_id + ')"')
			update_config("/tmp/tkTermrs" + term_id)
		sleep(0.05)

def commands():
	while not os.path.isfile("/tmp/tkTerm" + term_id):
		sleep(0.5)
	lastinit["/tmp/tkTerm" + term_id] = 0
	while True:
		if has_file_changed("/tmp/tkTerm" + term_id):
			line=subprocess.check_output(['true'], shell=True)
			os.system('bash -c "$(echo "echo -n >/tmp/tkTerm' + str(term_id) + '" && cat /tmp/tkTerm' + str(term_id) + ' | grep .)"')
			
			update_config("/tmp/tkTerm" + term_id)
		sleep(0.05)
thread1 = threading.Thread(target=auto_resize)
thread2 = threading.Thread(target=commands)
thread1.start()
thread2.start()
thread1.join()
thread2.join()

